ifeq ($(OSTYPE),cygwin)
	RM=rm
	MKDIR=mkdir
	TARGET_EXTENSION=out
else ifeq ($(OS),Windows_NT)
	RM=del
	MKDIR=mkdir
	TARGET_EXTENSION=exe
else
	RM=rm
	MKDIR=mkdir
	TARGET_EXTENSION=out
endif

C_COMPILER=gcc

CFLAGS = -std=c99

SRC_FILES=main.c load_params.c verify_params.c energy1.c energy2.c energy3.c verify_output.c output.c plot.c
PROGNAME=swhs
TARGET=$(PROGNAME).$(TARGET_EXTENSION)
INC_DIRS= -I include
LIB_DIRS= -L lib
LIB_LINKS= -lsundials_cvode -lsundials_nvecserial

INPUT_FILES = $(wildcard *.in)
OUTPUT_FILES = $(patsubst %.in, %.out, $(INPUT_FILES))
GRAPH_FILES = $(patsubst %.in, %.png, $(INPUT_FILES))

.PHONY : results
results : $(OUTPUT_FILES) $(GRAPH_FILES)

%.png %.out : %.in $(SRC_FILES)
	$(C_COMPILER) $(CFLAGS) $(SRC_FILES) -o $(TARGET) $(INC_DIRS) $(LIB_DIRS) $(LIB_LINKS) -o $(TARGET)
	./$(TARGET) $*.in
	
.PHONY : clean
clean :
	rm -f $(OUTPUT_FILES)
	rm -f $(GRAPH_FILES)
	rm -f swhs.exe