ifeq ($(OSTYPE),cygwin)
	RM=rm
	MKDIR=mkdir
	TARGET_EXTENSION=out
else ifeq ($(OS),Windows_NT)
	RM=del
	MKDIR=mkdir
	TARGET_EXTENSION=exe
else
	RM=rm
	MKDIR=mkdir
	TARGET_EXTENSION=out
endif

C_COMPILER=gcc

CFLAGS = -std=c99

TST_CFLAGS = -Wall
TST_CFLAGS += -Wextra
TST_CFLAGS += -Werror
TST_CFLAGS += -Wpointer-arith
TST_CFLAGS += -Wcast-align
TST_CFLAGS += -Wwrite-strings
TST_CFLAGS += -Wswitch-default
TST_CFLAGS += -Wunreachable-code
TST_CFLAGS += -Winit-self
TST_CFLAGS += -Wmissing-field-initializers
TST_CFLAGS += -Wno-unknown-pragmas
TST_CFLAGS += -Wstrict-prototypes
TST_CFLAGS += -Wundef
TST_CFLAGS += -Wold-style-definition
TST_CFLAGS += -Wmissing-prototypes
TST_CFLAGS += -Wmissing-declarations
TST_CFLAGS += -DUNITY_FIXTURES

SRC_FILES=main.c load_params.c verify_params.c energy1.c energy2.c energy3.c verify_output.c output.c plot.c
PROGNAME=swhs
TARGET=$(PROGNAME).$(TARGET_EXTENSION)
INC_DIR= -I include
LIB_DIRS= -L lib
LIB_LINKS= -lsundials_cvode -lsundials_nvecserial

TST_DIR = Testing
TST_SRC_FILES =\
  $(TST_DIR)/src/test_runners/testAll.c \
  $(TST_DIR)/src/unity.c \
  $(TST_DIR)/src/unity_fixture.c \
  $(TST_DIR)/src/unrecommendedInputTest.c \
  $(TST_DIR)/src/invalidInputTest.c \
  $(TST_DIR)/src/loadParamsTest.c \
  $(TST_DIR)/src/energyTest.c \
  $(TST_DIR)/src/verifyOutputTest.c \
  $(TST_DIR)/src/test_runners/unrecommendedInputTestRunner.c \
  $(TST_DIR)/src/test_runners/invalidInputTestRunner.c \
  $(TST_DIR)/src/test_runners/loadParamsTestRunner.c \
  $(TST_DIR)/src/test_runners/energyTestRunner.c \
  $(TST_DIR)/src/test_runners/verifyOutputTestRunner.c \
  verify_params.c \
  load_params.c \
  energy1.c \
  energy2.c \
  energy3.c \
  verify_output.c

TST_INC_DIR = -I $(TST_DIR)/include
TST_TARGET = tests.$(TARGET_EXTENSION)
  

INPUT_FILES = $(wildcard *.in)
OUTPUT_FILES = $(patsubst %.in, %.out, $(INPUT_FILES))
GRAPH_FILES = $(patsubst %.in, %.png, $(INPUT_FILES))

.PHONY : results
results : $(OUTPUT_FILES) $(GRAPH_FILES)

%.png %.out : %.in $(SRC_FILES)
	$(C_COMPILER) $(CFLAGS) $(SRC_FILES) -o $(TARGET) $(INC_DIR) $(LIB_DIRS) $(LIB_LINKS) -o $(TARGET)
	./$(TARGET) $*.in

.PHONY : tests
tests : 

	$(C_COMPILER) $(CFLAGS) $(TST_CFLAGS) $(INC_DIR) $(TST_INC_DIR) $(TST_SRC_FILES) -o $(TST_TARGET)
	./$(TST_TARGET)
	
.PHONY : clean
clean :
	rm -f $(OUTPUT_FILES)
	rm -f $(GRAPH_FILES)
	rm -f swhs.exe